// ❌ Remove this line:
// "use client"; ← hata do

import { Poppins } from "next/font/google";
import "./globals.css";
import { Providers, ThemeProvider } from './providers';
import 'antd/dist/reset.css';
import { ConfigProvider } from "antd";
import AppNotifications from '../components/AppNotifications';
import ClientWrapper from "../components/ClientWrapper"; // ✅ new wrapper

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "TalkHub",
  description: "Generated by create Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <Providers>
            <ClientWrapper> {/* ✅ Hook will run here */}
              <AppNotifications />
              {children}
            </ClientWrapper>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
