import { Poppins } from "next/font/google";
import "./globals.css";
import { Providers, ThemeProvider } from './providers';
import 'antd/dist/reset.css';
import { ConfigProvider } from "antd";
import AppNotifications from '../components/AppNotifications';
import ClientWrapper from "../components/ClientWrapper";
import { GoogleOAuthProvider } from '@react-oauth/google';

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "TalkHub",
  description: "Generated by create Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script
          async
          defer
          crossOrigin="anonymous"
          src="https://connect.facebook.net/en_US/sdk.js"
        />
      </head>
      <body>
        <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID}>
          <ThemeProvider>
            <Providers>
              <ClientWrapper>
                <AppNotifications />
                {children}
              </ClientWrapper>
            </Providers>
          </ThemeProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}